version: '3'
services:
    app:
        build: .
        volumes:
            - ./:/home/app
        ports:
            - 4200:4200
        command: ng serve --host 0.0.0.0 --port 4200 --poll 1 --disable-host-check
